export const EU14_ALLERGENS = [
  { id: 'gluten_cereals', label: 'Gluten (wheat, rye, barley, oats)' },
  { id: 'crustaceans',    label: 'Crustaceans (shrimp, crab, lobster)' },
  { id: 'eggs',           label: 'Eggs' },
  { id: 'fish',           label: 'Fish' },
  { id: 'peanuts',        label: 'Peanuts' },
  { id: 'soybeans',       label: 'Soy / Soja' },
  { id: 'milk',           label: 'Milk / Dairy (lactose)' },
  { id: 'tree_nuts',      label: 'Tree Nuts (almonds, hazelnuts, walnuts etc.)' },
  { id: 'celery',         label: 'Celery' },
  { id: 'mustard',        label: 'Mustard' },
  { id: 'sesame',         label: 'Sesame' },
  { id: 'sulphites',      label: 'Sulphites / Sulphur dioxide' },
  { id: 'lupin',          label: 'Lupin' },
  { id: 'molluscs',       label: 'Molluscs (squid, mussels, oysters)' },
] as const;
